### ISSUE TITLE
How to fetch the latest identity info after the service is updated?

### ISSUE THREAD

**Issue by hoocbee** [apple/live-caller-id-lookup-example#23]
Hi,

I wonder how the client could fetch the updated number identity info after the server updates input.txtpb?

At first, the content of my input.txtpb file was like this:
 
![图片 1](https://github.com/user-attachments/assets/541ed0a6-3dc4-4239-9dd0-346ff898f6fa)

After executing the `ConstructDatabase`, `PIRProcessDatabase` and `PIRService` commands, I installed my App and turned on the LIVE CALLERID LOOKUP, and successfully displayed "ID1" when the call came in.
![图片 2](https://github.com/user-attachments/assets/f883b79f-4732-4e75-8141-0d50b8d15fa4)
 

Then, I changed the name of the input.txtpb file from “ID1” to "ID2".
However, after I re-executed the `ConstructDatabase`, `PIRProcessDatabase` and `PIRService` commands:

-  After "ID1" expires (5 minutes as configured above), when the same call comes in, the name I fetch is empty.
![图片 3](https://github.com/user-attachments/assets/f91ac98d-128f-45cc-9b62-6cdfe872fab7)

 
- Only after I execute the `LiveCallerIDLookupManager.shared.reset` and `LiveCallerIDLookupManager.shared.refreshPIRParameters` methods in the app can I fetch the "ID2" normally

I wonder what is the correct way to do this? Or is there a bug here? From the API comments of `LiveCallerIDLookupManager`, it seems that is not necessary to execute the `refreshPIRParameters` method when just modify the name?

**Comment by hoocbee** [comment]
In addition, if I only execute the `ConstructDatabase` and `PIRProcessDatabase` commands without executing the `PIRService` command after change the name of input.txtpb from "ID1" to "ID2" :
- After "ID1" expires, when the same call comes in, the name I fetch is still "ID1".

**Comment by karulont** [comment]
What happens, is that by restarting the server, you also invalidated a few other things: cached access tokens, evaluation key stored on server.

So that is the reason why you needed to use the `refreshPIRParameters`.

#22 adds some additional information about it.

**Comment by hoocbee** [comment]
So, if I modify the content of the input.txtpb file, do I have to restart the service?
As I added in the comment above, it seems that if the service is not restarted, the client will still fetch the old name ("ID1") . Is this as expected?

**Comment by karulont** [comment]
This is expected for the example service. It only loads the service-config and the usecases defined there at startup. So following changes to the files fill not affect the service until the service is restarted(which also invalidated a few keys).

**Comment by hoocbee** [comment]
Got it, thanks!

**Comment by minnow54426** [comment]
> Hi,
> 
> I wonder how the client could fetch the updated number identity info after the server updates input.txtpb?
> 
> At first, the content of my input.txtpb file was like this:
> 
> ![图片 1](https://github.com/user-attachments/assets/541ed0a6-3dc4-4239-9dd0-346ff898f6fa)
> 
> After executing the `ConstructDatabase`, `PIRProcessDatabase` and `PIRService` commands, I installed my App and turned on the LIVE CALLERID LOOKUP, and successfully displayed "ID1" when the call came in. ![图片 2](https://github.com/user-attachments/assets/f883b79f-4732-4e75-8141-0d50b8d15fa4)
> 
> Then, I changed the name of the input.txtpb file from “ID1” to "ID2". However, after I re-executed the `ConstructDatabase`, `PIRProcessDatabase` and `PIRService` commands:
> 
> * After "ID1" expires (5 minutes as configured above), when the same call comes in, the name I fetch is empty.
>   ![图片 3](https://github.com/user-attachments/assets/f91ac98d-128f-45cc-9b62-6cdfe872fab7)
> * Only after I execute the `LiveCallerIDLookupManager.shared.reset` and `LiveCallerIDLookupManager.shared.refreshPIRParameters` methods in the app can I fetch the "ID2" normally
> 
> I wonder what is the correct way to do this? Or is there a bug here? From the API comments of `LiveCallerIDLookupManager`, it seems that is not necessary to execute the `refreshPIRParameters` method when just modify the name?

Hello, now i have run PIRService successfully, you wrote that "i installed my app and turned on the LIVE CALLERID LOOKUP", can you say more details about this? After starting the PIRService, the document only says that we need a LiveCallerIDLookupExtensionContext, however I don't know anything about where to create this context and how to use it.
Thanks very much

**Comment by karulont** [comment]
Please see the documentation at https://developer.apple.com/documentation/identitylookup/getting-up-to-date-calling-and-blocking-information-for-your-app

**Comment by karulont** [comment]
Also wanted to add: that we added a way for the service to reload the configuration without having to restart the service.

#47
