### ISSUE TITLE
The data is too much, a timeout will be displayed.

### ISSUE THREAD

**Issue by sanjinhub** [apple/live-caller-id-lookup-example#31]
When I test with 10,000 data entries, a timeout occurs; however, testing with just a few entries works perfectly fine.

![WX20240914-183227@2x](https://github.com/user-attachments/assets/ba400999-0cbf-4e95-85e3-07b6a849327c)

**Comment by fboemer** [comment]
https://swiftpackageindex.com/apple/live-caller-id-lookup-example/main/documentation/pirservice/testinginstructions#Processing-the-datasets has some information on processing the datasets. In particular, the [Parameter Tuning documentation](https://swiftpackageindex.com/apple/swift-homomorphic-encryption/main/documentation/privateinformationretrieval/parametertuning) will be helpful to achieve best performance.

You can try using more shards, e.g. via decreasing `entryCountPerShard` or, equivalently, increasing `shardCount`.
