### ISSUE TITLE
 Add new identity to the database without needing to restart the server

### ISSUE THREAD

**Issue by glebfann** [apple/live-caller-id-lookup-example#51]
Hello! I am reaching out to request a feature enhancement for this example: the ability to add new identities to the database without needing to restart the server. This update should not necessitate the use of `refreshPIRParameters` on the client side.
Implementing this feature would greatly benefit the community by providing a clearer understanding of how the service can effectively operate in a production environment.

**Comment by karulont** [comment]
#47 added support for reloading the dataset.

See [Reusing PIR Parameters](https://swiftpackageindex.com/apple/swift-homomorphic-encryption/1.0.2/documentation/privateinformationretrieval/reusingpirparameters) on how to preprocess the dataset in a way that the client configuration does not need to be changed, i.e `refreshPIRParameters` does not need to be called on the client side.
